name: priori_care
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch=2.1.2
  - pytorch::pytorch-cuda=11.8
  - pip
  - pip:
      - transformers==4.36.2
      - accelerate==0.25.0
      - sentencepiece==0.1.99
      - protobuf==4.25.1
      - rouge-score==0.1.2
      - tqdm==4.66.1